# Do not forget to create the .env file (see template)
# before using this container!

services:
    www:
        restart: always
        build: .
        environment:
            PORT: 8080
            ACTIONABLES_URL: $ACTIONABLES_URL
        ports:
            - $PORT:80
